<?php 
$form->prepare(); 
$escapeHtml = $this->plugin('escapeHtml');
?>
<h1><?php echo $escapeHtml($this->translate('Fedora Connector')); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag($form); ?>