<?php
/*
 * Copyright BibLibre, 2016
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $resourceName = $resource->resourceName(); ?>
<?php
    if ($resourceName === 'item_sets') {
        $q = [
            'itemSet' => [
                'ids' => [$resource->id()],
            ],
        ];
        $resourceUrl = $this->url('search-page-' . $this->themeSetting('search_page_id'), [], ['query' => $q], true);
    } else {
        $resourceUrl = $resource->url();
    }
?>

<div class="<?php echo $resourceName; ?> resource">
    <div class="resource-thumbnail">
        <?php
            if ($resourceName === 'media') {
                $media = $resource;
            } else {
                $media = $resource->primaryMedia();
            }
        ?>

        <?php if ($media): ?>
            <a href="<?php echo $this->escapeHtml($resourceUrl); ?>">
                <img
                    src="<?php echo $escape($media->thumbnailUrl('square')); ?>"
                    title="<?php echo $escape($media->displayTitle()); ?>"
                    alt="<?php echo $escape($media->mediaType()); ?> thumbnail"
                />
            </a>
        <?php endif; ?>
    </div>
    <div class="resource-metadata">
        <h4>
            <?php if ($resourceName === 'items' || $resourceName === 'media'): ?>
                <?php echo $this->updateBasketLink($resource); ?>
            <?php endif; ?>
            <a href="<?php echo $this->escapeHtml($resourceUrl); ?>"><?php echo $resource->displayTitle(); ?></a>
        </h4>
        <?php if ($resourceName === 'item_sets'): ?>
            <div class="items-count">
                <?php echo $resource->itemCount() == 1 ? '1 contenu' : sprintf('%s contenus', $resource->itemCount()); ?>
            </div>
        <?php endif; ?>
        <?php
            $properties = [
                'dcterms:creator' => 'Créateur',
                'dcterms:publisher' => 'Éditeur',
                'dcterms:created' => 'Date de création',
                'dcterms:type' => 'Type',
                'dcterms:source' => 'Source',
                'dcterms:subject' => 'Sujet',
                'dcterms:identifier' => 'Identifiant',
            ];
        ?>
        <?php foreach ($properties as $term => $label): ?>
            <?php $value = $resource->value($term, ['type' => 'literal']); ?>
            <?php if ($value): ?>
                <div class="<?php echo str_replace(':', '-', $term); ?>">
                    <span><?php echo $value; ?></span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
