<?php
    $text = $action === 'add' ? $this->translate('Add to basket') : $this->translate('Remove from basket');
    $class = "basket-$action";
?>
<button class="basket-update <?php echo $class; ?>" title="<?php echo $text ;?>" data-url="<?php echo $url ?>">
    <?php
        echo $this->partial('basket/basket-button-content', [
            'action' => $action,
            'text' => $text,
        ]);
    ?>
</button>
