<?php
 $form->prepare();
 echo $this->form()->openTag($form);
 ?>


<div class="field">

<?php echo $this->formRow($form->get('guest_user_capabilities')); ?>
<?php echo $this->formRow($form->get('guest_user_short_capabilities')); ?>
<?php echo $this->formRow($form->get('guest_user_dashboard_label')); ?>
<?php echo $this->formRow($form->get('guest_user_login_text')); ?>
<?php echo $this->formRow($form->get('guest_user_register_text')); ?>
</div>
